# Ruta del archivo JSON de las credenciales de la cuenta de servicio de Google Cloud.
credentials_path: credencial.json

# ID del proyecto en Google Cloud. Este valor identifica tu proyecto en Google Cloud.
project_id: proyecto 

# Nombre del bucket en Google Cloud Storage donde se subir치 el archivo.
bucket_name: nombre_del_bucket 

# Nombre del t칩pico en Google Pub/Sub donde se publicar치 el mensaje.
topic_name: nombre_del_topico 

# Nombre del archivo CSV que se subir치 a Google Cloud Storage.
csv_filename: archivo.csv
# Separador del archivo
separador: ";"
